@startsalt
{+

  {+
    "//Header//                                   "
  }
'------------------------

  {+
    {/ <b>Menu | General | Fullscreen | Behavior | Saving }
  }


'------------------------
  {
    //Body//
    .
    "                                             "
  }

'------------------------

  {+
    //Sub// 
    .
    "                                             "

    {+
      This is a long
      text in a textarea
      .
      "                                             "
    }
  }

'------------------------

  {+
    "//Foother//                                  "
  }
}
@endsalt